services:
  - type: web
    name: spotiflow
    env: python
    runtime: python3
    buildCommand: |
      # Exit on error
      set -o errexit

      echo "Current directory: $(pwd)"

      pip install -r requirements.txt

      export PYTHONPATH=$PYTHONPATH:$(pwd)
      echo "PYTHONPATH: $PYTHONPATH"

      echo "Files in current directory:"
      ls -la

      echo "Checking for spotiflow module:"
      find . -name "*.py" | grep -i spotiflow
      echo "Tesseract path (build phase): $(which tesseract)"

      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      echo "Runtime Tesseract:" && which tesseract && \
      PYTHONPATH=$PYTHONPATH:$(pwd) gunicorn spotiflow.wsgi:application --bind 0.0.0.0:$PORT
    apt:
      packages:
        - tesseract-ocr
